version: "3"
services:
  client:
    container_name: app-geolocation
    restart: on-failure
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  server:
    container_name: server
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  mongo:
    image: mongo
    restart: on-failure
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example